environment:
  global:
    PYPI_USER: ifduyue
    PYPI_TEST_PASSWORD:
      secure: Ub5TGKonq/xFgzRLFMCcKQ==
    PYPI_PASSWORD:
      secure: fFfFN5N5920gtX3+pwrOddk/psDk3wK67snCOt209bc=
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"
    - PYTHON: "C:\\Python39"
    - PYTHON: "C:\\Python39-x64"
    - PYTHON: "C:\\Python310"
    - PYTHON: "C:\\Python310-x64"
    # build wheels
    - PYTHON: "C:\\Python36-x64"
      XXTEA_BUILDWHEELS: 1

build: off

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - git --version
  - python --version
  - pip --version
  - pip install --user --upgrade wheel setuptools

test_script:
  - python setup.py build
  - python setup.py test
  - ps: |
      if (Test-Path env:XXTEA_BUILDWHEELS) {
        python -m pip install -U pip setuptools cibuildwheel
        cibuildwheel --output-dir wheels
        ls wheels
      }

artifacts:
  - path: wheels\*.whl
    name: Wheels

on_success:
  # deploy master non-tags to Test PyPI
  - ps: |
      if (!(Test-Path env:XXTEA_BUILDWHEELS)) { return }
      if (Test-Path env:APPVEYOR_PULL_REQUEST_NUMBER) { return }
      if ($env:APPVEYOR_REPO_NAME -ne 'ifduyue/xxtea') { return }
      if ($env:APPVEYOR_REPO_BRANCH -ne 'master') { return }
      pip install -U twine
      twine upload -u $env:PYPI_USER -p $env:PYPI_TEST_PASSWORD --repository-url https://test.pypi.org/legacy/ --skip-existing wheels\*.whl

  # deploy tags to PyPI
  - ps: |
      if (!(Test-Path env:XXTEA_BUILDWHEELS)) { return }
      if (Test-Path env:APPVEYOR_PULL_REQUEST_NUMBER) { return }
      if ($env:APPVEYOR_REPO_NAME -ne 'ifduyue/xxtea') { return }
      if ($env:APPVEYOR_REPO_TAG -ne 'true') { return }
      pip install -U twine
      twine upload -u $env:PYPI_USER -p $env:PYPI_PASSWORD --skip-existing wheels\*.whl
